export const EVENT_TYPES = {
  APPOINTMENT_CONFIRMED: "APPOINTMENT_CONFIRMED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  APPOINTMENT_RESCHEDULED: "APPOINTMENT_RESCHEDULED",
  PROVIDER_SCHEDULE_UPDATED: "PROVIDER_SCHEDULE_UPDATED",
  PROVIDER_AVAILABILITY_CHECKED: "PROVIDER_AVAILABILITY_CHECKED",
} as const
